### ISSUE TITLE
Using eqref instead of ref for latex output

### ISSUE THREAD

**Issue by JeanOlivier** [tomduck/pandoc-eqnos#27]
Would it be possible to have an option to use \eqref instead of \ref for latex outputs?

\eqref puts parentheses around the equation number, e.g. `eq. (1)` instead of `eq. 1`.

It might also be nice to reproduce this in html if the option is enabled, so the documents are more uniform across formats.

I read pandoc_eqnos.py and I see no obvious way to do so, but I'm not used to pandocfilters and pandocxnos. If someone would like to implement this, or point me towards the right way to do so, I'd appreciate it a lot.

Thank you!

**Comment by tomduck** [comment]
Thanks, @JeanOlivier.  This is a good idea, and currently isn't possible in pandoc-fignos/eqnos/tablenos.  It should be straight-forward to implement.  Stay tuned!

**Comment by JeanOlivier** [comment]
Thank you for your fast answer!

Just to point out that, in my opinion, this feature would *not* be pertinent in fignos/tablenos. While the `\eqref` command will work in conjunction with any defined `\label`, it should normally be reserved for equations.

Cheers!

*Edited for clarity because I had forgot the *not*.

**Comment by tomduck** [comment]
I just pushed out a new release that enables AMS-style equations referencing.  You simply need to set `eqnos-eqref: On` in your metadata block.

Please let me know if you have any difficulties with it.  Thanks again for the suggestion.

**Comment by JeanOlivier** [comment]
First of all, thanks for taking the time to implement this, I appreciate it a lot.

Sadly, though, it seems I can't manage to make it work.

Minimum example:
``` markdown
---
eqnos-cleveref:     Off
eqnos-plus-name:    eq.
eqnos-eqref:        On
---

# Test
Here's Newton second law.
$$ F=ma $$ {#eq:NewtonSecondLaw}

As stated before, {+@eq:NewtonSecondLaw} is Newton second law. You can refer to it as {@eq:NewtonSecondLaw} too.
```

I compile using `pandoc test.md --filter pandoc-eqnos -o test.pdf -s`

I get the following output in the PDF (same for html), with the ones being proper hyperlinks:

> As stated before, eq. 1 is Newton second law. You can refer to it as 1 too.

Whereas I'm expecting

> As stated before, eq. (1) is Newton second law. You can refer to it as (1) too.


What am I missing?

**Comment by JeanOlivier** [comment]
I have verified my versions and I am using:

- pandoc 1.16.0.2
- pandoc-xnos 1.0.1
- pandoc-eqnos 1.2.0

I read your associated commits and the logic seems fine, yet it still doesn't work for me. I noticed there were some cython cache files included in the python3 version of the package, maybe those are still of the old version? I'm probably grasping at straws here.

Edit: @tomduck, I'm tagging you because I don't know if you get notifications on a closed issue and I don't want to open a duplicated issue.

**Comment by JeanOlivier** [comment]
@tomduck Any thoughts on this? Maybe I'm doing something wrong?

**Comment by tomduck** [comment]
Sorry, I did not see these follow-ups after the Issue was closed.  I believe this is asking the same thing as Issue #57, which is what brought me back here.  I will leave this closed and will continue the discussion through Issue #57.  --Tom

**Comment by tomduck** [comment]
A new version of pandoc-eqnos was just released that does what you want (I think!).  Please see Issue #57.  --Tom
