### ISSUE TITLE
id attribute gets lost when output type is epub3

### ISSUE THREAD

**Issue by cplerch** [tomduck/pandoc-eqnos#37]
Although all references are rendered correctly in the output document, all equation ids are missing in epub3 output.
However, when I convert the very same source files to html output everything works as expected.
I'm using pandoc 2.7 with pandoc-eqnos 1.3.0

**Comment by tomduck** [comment]
Hi, Christian.  Thanks for your feedback.  I am able to reproduce this issue.  Interestingly, links to figures seem to work just fine.  I will look into it.  Cheers, Tom.

**Comment by tomduck** [comment]
I just posted a new version which fixes the problem.  If you have any difficulty with it, please go ahead and re-open this issue.  Thanks again for your feedback, which is much appreciated.

**Comment by cplerch** [comment]
Thanks for the fix. After testing it there is a minor issue still remaining.
It works as expected for fmt='epub' but for fmt='epub3' the id attributes are still missing. The behavior for both of these output formats should be equivalent, because they can be used synonymously.
Didn't test fmt='epub2' however; maybe same problem.

**Comment by cplerch** [comment]
Checked again and just realized that: 
If you convert to output format "epub" (instead of "epub3") you now get all equations numbered twice, like this:
![1558100449691](https://user-images.githubusercontent.com/8402395/57932076-5661a200-78ba-11e9-9211-fafcf1280338.png)
Using output format "epub3" you get:
![1558100922906](https://user-images.githubusercontent.com/8402395/57932522-5ca44e00-78bb-11e9-9510-0e3eb28bd3a0.png)
which isn't optimal but at least acceptable (will open another issue for proposing a solution for rendering the equation number on the right margin, where it belongs).

**Comment by tomduck** [comment]
Yep, I saw that too and have a fix for it.  I will be pushing out a new version shortly.

It looks like epub infers the figure number from the id in the surround span.  Interesting.

**Comment by tomduck** [comment]
I pushed out a new version.  Please give it a try and let me know what you think.

**Comment by cplerch** [comment]
I'm afraid the numbering still doesn't work as expected, however the original subject of THIS issue (id attributes) is OK. I will create a new issue or the numbering problem I'm experiencing.
